[package]
name = "testgame"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# normally:
# mtg-rust = { git = "https://github.com/Benonardo/mini-tardis-games" }
mtg-rust = { path = "../" }
glam = "0.25.0"
